# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-26 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null='True')),
                ('last_name', models.CharField(max_length=100, null='True')),
                ('email', models.EmailField(max_length=100, null='True')),
                ('ph_number', models.IntegerField(null='True')),
                ('address', models.CharField(max_length=100, null='True')),
                ('company_name', models.CharField(max_length=100, null='True')),
                ('gst_no', models.IntegerField(null='True')),
            ],
        ),
    ]
