# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-30 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Final_products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, null='True')),
                ('description', models.TextField(blank=True)),
                ('pic', models.FileField(null='True', upload_to='pic')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Categories')),
            ],
        ),
        migrations.RenameModel(
            old_name='Client',
            new_name='Clients',
        ),
    ]
