# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-03 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_pics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(null='True', upload_to='pic')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Categories')),
            ],
        ),
    ]
